# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: "Brian McLaughlin"
title: SpinStabilized's Home
subtitle: "My Little Corner of The Web"
email: bjmclaughlin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Homepage for SpinStabilized.
domain: spinstabilized.github.io
repository: "SpinStabilized/spinstabilized.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spinstabilized.github.io"
github_username:  SpinStabilized
locale: "en-US"
timezone: America/New_York
title_separator: "|"
markdown: kramdown

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-include

# Search Options
search: true
lunr:
  search_within_pages: true

# Include the "_pages" directory and sub-direcoty
include: ["_pages", "_pages/stem"]

# Layout Default Settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      related: true

# Site Author Information
author:
  name: "Brian McLaughlin"
  avatar: "/assets/images/head_shot.jpeg"
  bio: >-
    Geek, Maker, Engineer, former NASA, former [GeekDad](https://geekdad.com/). Opinions expressed here are my own. He/Him.
  location: "Maryland, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/spinstabilized"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/Spin-Stabilized"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/spinstabilized/"